# Generated by Django 5.1.4 on 2024-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carname", models.CharField(max_length=64)),
                ("brand", models.CharField(max_length=64)),
                ("year", models.IntegerField()),
                ("owner", models.CharField(max_length=64)),
            ],
        ),
    ]
